export const medicalHistoryOptions = [
  { title: "Asthma" },
  { title: "Diabetes" },
  { title: "High Blood Pressure" },
  { title: "Hypertension" },
  { title: "Heart Disease" },
  { title: "Kidney Disease" },
  { title: "ALS" },
  { title: "Alzheimer's Disease" },
  { title: "Dementia" },
  { title: "Parkinson's Disease" },
  { title: "Myasthenia Gravis" },
  { title: "Guillain-Barre Syndrome" },
  { title: "ESRD" },
  { title: "Liver Disease" },
  { title: "Thyroid Disease" },
  { title: "Depression" },
  { title: "Anxiety" },
  { title: "Bipolar Disorder" },
  { title: "Schizophrenia" },
  { title: "Autism" },
  { title: "ADHD" },
  { title: "ADD" },
  { title: "Down Syndrome" },
  { title: "Brain Cancer" },
  { title: "Cancer" },
  { title: "Pancreatic Cancer" },
  { title: "Breast Cancer" },
  { title: "Prostate Cancer" },
  { title: "Lung Cancer" },
  { title: "Colon Cancer" },
  { title: "Skin Cancer" },
  { title: "Bladder Cancer" },
  { title: "Kidney Cancer" },
  { title: "Liver Cancer" },
  { title: "Ovarian Cancer" },
  { title: "Uterine Cancer" },
  { title: "Thyroid Cancer" },
  { title: "Leukemia" },
  { title: "Lymphoma" },
  { title: "Melanoma" },
  { title: "Non-Hodgkin's Lymphoma" },
  { title: "Hodgkin's Lymphoma" },
  { title: "Multiple Myeloma" },
  { title: "Osteosarcoma" },
  { title: "Rhabdomyosarcoma" },
  { title: "Sarcoma" },
  { title: "Testicular Cancer" },
  { title: "Thymoma" },
  { title: "HIV/AIDS" },
  { title: "Hepatitis" },
  { title: "Tuberculosis" },
  { title: "Arthritis" },
  { title: "Rheumatoid Arthritis" },
  { title: "Osteoarthritis" },
  { title: "Gout" },
  { title: "Psoriatic Arthritis" },
  { title: "Lupus" },
  { title: "Sjogren's Syndrome" },
  { title: "Scleroderma" },
  { title: "Epilepsy" },
  { title: "Migraines" },
  { title: "Multiple Sclerosis" },
  { title: "Muscular Dystrophy" },
  { title: "Cerebral Palsy" },
  { title: "Cystic Fibrosis" },
  { title: "Sickle Cell Disease" },
  { title: "Thalassemia" },
  { title: "Lyme Disease" },
  { title: "Celiac Disease" },
  { title: "Crohn's Disease" },
  { title: "Ulcerative Colitis" },
  { title: "Irritable Bowel Syndrome" },
  { title: "Hashimoto's Disease" },
  { title: "Cushing's Disease" },
  { title: "Graves' Disease" },
  { title: "Hypothyroidism" },
  { title: "Hyperthyroidism" },
  { title: "Tourette's Syndrome" },
  { title: "COPD" },
  { title: "Emphysema" },
  { title: "Chronic Bronchitis" },
  { title: "Heart Failure" },
  { title: "Coronary Artery Disease" },
  { title: "Peripheral Artery Disease" },
  { title: "Congestive Heart Failure" },
  { title: "Stroke" },
  { title: "Transient Ischemic Attack" },
  { title: "Aneurysm" },
  { title: "Atrial Fibrillation" },
  { title: "Cardiomyopathy" },
  { title: "Congenital Heart Disease" },
];

export const surgicalHistoryOptions = [
  { title: "Appendectomy" },
  { title: "Bariatric Surgery" },
  { title: "Bypass Surgery" },
  { title: "Cataract Surgery" },
  { title: "Cesarean Section" },
  { title: "Cholecystectomy" },
  { title: "Colonoscopy" },
  { title: "Colorectal Surgery" },
  { title: "Colostomy" },
  { title: "Cystoscopy" },
  { title: "Cystourethroscopy" },
  { title: "Coronary Artery Bypass Graft" },
  { title: "Coronary Angioplasty" },
  { title: "Coronary Stent" },
  { title: "Cystectomy" },
  { title: "D&C" },
  { title: "Dental Surgery" },
  { title: "Hysterectomy" },
  { title: "Knee Replacement" },
  { title: "Knee Surgery" },
  { title: "Knee Arthroscopy" },
  { title: "Knee Arthroplasty" },
  { title: "Laparoscopic Surgery" },
  { title: "Lap Band Surgery" },
  { title: "Lumpectomy" },
  { title: "Mastectomy" },
  { title: "Mastoidectomy" },
  { title: "Nephrectomy" },
  { title: "Oophorectomy" },
  { title: "Ovarian Cystectomy" },
  { title: "Ankle Arthroscopy" },
  { title: "Ankle Surgery" },
  { title: "Ankle Fusion" },
  { title: "Ankle Arthroplasty" },
  { title: "Lumbar Fusion" },
  { title: "Lumbar Discectomy" },
  { title: "Lumbar Laminectomy" },
  { title: "Cervical Fusion" },
  { title: "Cervical Discectomy" },
  { title: "Cervical Laminectomy" },
  { title: "Cervical Laminoplasty" },
  { title: "Cervical Laminotomy" },
  { title: "Cervical Spine Fusion" },
  { title: "Percutaneous coronary angioplasty" },
  { title: "Percutaneous transluminal coronary angioplasty" },
  { title: "Partial excision of bone" },
  { title: "Colorectal resection" },
  { title: "Colon resection" },
  { title: "Rectal resection" },
  { title: "Rectosigmoid resection" },
  { title: "Sigmoid resection" },
  { title: "Small bowel resection" },
  { title: "Excision, lysis peritoneal adhesions" },
  { title: "Excision, lysis of retroperitoneal adhesions" },
  { title: "Oophorectomy, unilatera" },
  { title: "Oophorectomy, bilateral" },
  {
    title:
      "Treatment, fracture or dislocation of lower extremity (other than hip or femur)",
  },
  { title: "Transurethral prostatectomy" },
  { title: "Peripheral vascular bypass" },
  { title: "Creation of arteriovenous fistula" },
  { title: "Revision of arteriovenous fistula" },
  { title: "Removal of arteriovenous fistula" },
  {
    title:
      "	Insertion, replacement, or removal of extracranial ventricular shunt",
  },
  { title: "Inguinal and femoral hernia repair" },
  { title: "Umbilical hernia repair" },
  { title: "Incisional hernia repair" },
  { title: "Heart valve replacement" },
  { title: "Tonsillectomy and/or adenoidectomy" },
  { title: "Hip replacement, total and/or partial" },
  { title: "Common duct exploration" },
  { title: "Other open heart surgery" },
  { title: "Carotid endarterectomy" },
  { title: "Cataract surgery" },
  { title: "Skin graft" },
];
